<?php

namespace App\Services;

use App\Repository\MyTableRepository;
use App\Repository\SqliteRepository;
use DB;

/**
 * 连接帮助类
 *
 *
 */
class ConnectionService
{

    public function createConfig()
    {
        $sqliteRepository = new SqliteRepository();
        $connectionList = $sqliteRepository->getAllConnections()
            ->map(function ($connection) {
                return [
                    'driver' => 'mysql',
                    'host' => $connection->host,
                    'port' => $connection->port,
                    'database' => $connection->db_name,
                    'username' => $connection->username,
                    'password' => $connection->password,
                    'charset' => 'utf8',
                    'connection' => $connection->connection,

                ];
            })->keyBy('connection')->map(function ($connection){
                unset( $connection['connection'] );
                return $connection;
            }) ->all();

        $code = <<<PHP
<?php

//The following code is generated by the program

return

PHP;
        $code .= var_export($connectionList, true);
        $code .= ';'."\n";

        file_put_contents(config_path('mydb.php'), $code);

    }


}
